[Audio]
PreferredLanguage=eng
Volume=50

[General]
FileDialogLastLocation=file:///home/sinder/Videos/GHOST in the SHELL (1995-2015) - 3 Movies, COMPLETE Stand Alone Complex SERIES, Arise OVAs - 1080p DUAL Audio x264/b. STAND Alone COMPLEX (2002-06)/1a. 1st Gig (2002-03)
FloatingFooterTrigger=BottomMouseMovement
FooterStyle=floating
LastPlayedFile=file:///home/sinder/Downloads/%5BFLE%5D Re ZERO Starting Life in Another World - S00E55-E70 (BD Remux 1080p x264 FLAC)/%5BFLE%5D Re ZERO Starting Life in Another World - S00E70 (BD Remux 1080p x264 FLAC) %5BAF8BD39B%5D.mkv
ShowMenuBar=false

[Playlist]
CanToggleWithMouse=false
Style=withThumbnails
Visible=true

[Video]
ScreenshotFormat=png
