[Audio]
PreferredLanguage=eng
Volume=65

[General]
FileDialogLastLocation=file:///home/sinder/Videos/GHOST in the SHELL (1995-2015) - 3 Movies, COMPLETE Stand Alone Complex SERIES, Arise OVAs - 1080p DUAL Audio x264/b. STAND Alone COMPLEX (2002-06)/1a. 1st Gig (2002-03)
FloatingFooterTrigger=BottomMouseMovement
FooterStyle=floating
LastPlayedFile=file:///home/sinder/Music/japan.mp3
ShowMenuBar=false

[Playlist]
CanToggleWithMouse=false
Style=withThumbnails

[Video]
ScreenshotFormat=png
