[Audio]
PreferredLanguage=eng
Volume=65

[General]
FileDialogLastLocation=file:///home/sinder/Videos/GHOST in the SHELL (1995-2015) - 3 Movies, COMPLETE Stand Alone Complex SERIES, Arise OVAs - 1080p DUAL Audio x264/b. STAND Alone COMPLEX (2002-06)/1a. 1st Gig (2002-03)
FloatingFooterTrigger=BottomMouseMovement
FooterStyle=floating
LastPlayedFile=file:///home/sinder/Downloads/%5BJudas%5D Mushishi (Seasons 1-3 + Movie + Special) %5BBD 1080p%5D%5BHEVC x265 10bit%5D%5BEng-Subs%5D/%5BJudas%5D Mushishi S2/%5BJudas%5D Mushishi - S2E03.mkv
ShowMenuBar=false

[Playback]
RestoreFilePosition=true

[Playlist]
CanToggleWithMouse=false
RememberState=true
Style=withThumbnails

[Video]
ScreenshotFormat=png
